---
# Documentation: https://github.com/amannn/action-semantic-pull-request
name: "Lint PR"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
    name: "Validate PR Title"
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BACKUP_TOKEN }}
        with:
          types: |
            fix
            feat
            refactor
            docs
            test
            perf
            chore
            style
            ci
            build
          requireScope: true
          wip: true
          validateSingleCommit: false
          headerPattern: '^(\w*)(?:\(([\w$.\-*/ ]*)\))?: (.*)$'
          headerPatternCorrespondence: type, scope, subject
