---
name: Release
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BACKUP_TOKEN }}
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/commit-analyzer@v9.0.2
            @semantic-release/changelog@v6.0.1
            @semantic-release/git@v10.0.1
            conventional-changelog-conventionalcommits@5.0.0
